name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go-version: [ "1.21" ]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: go build ci
        run: |
          echo 'Build Stage Started'
          mkdir -p .build
          go mod init basic_go/v2
          go mod tidy
          go build main.go
          cp go.mod .build/go.mod.orig
          echo 'Build Stage Ended'
        shell: bash

  test:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go-version: [ "1.21" ]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: go test ci
        run: |
          echo 'Test Stage Started'
          go mod init basic_go/v2
          go test
          echo 'Test Stage Ended'
        shell: bash
  
  docker:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        go-version: [ "1.21" ]
    runs-on:  ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: go test ci
        run: |
          echo 'Docker Stage Started Now.'
          echo 'Docker Stage Ended'
        shell: bash
